steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dynamic-moment-441416-m2/app-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dynamic-moment-441416-m2/app-image']
images:
- 'gcr.io/dynamic-moment-441416-m2/app-image'
