steps:
- name: 'gcr.io/cloud-builders/docker'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/dynamic-moment-441416-m2/patel-docker/$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/dynamic-moment-441416-m2/patel-docker/$COMMIT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
